#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json
packaging_format = 2
id = "arcenal-store"
name = "ARCenal Store"
description.fr = "Active le catalogue ARCenal contrôlé dans YunoHost."
description.en = "Enables the controlled ARCenal catalog in YunoHost."
version = "1.1.0~ynh1"
maintainers = ["ARCenal"]

[upstream]
license = "GPL-3.0-or-later"
code = "https://github.com/arcenal-coder/arcenal-store_ynh"

[integration]
yunohost = ">= 12.1"
helpers_version = "2.1"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "1M"
ram.build = "10M"
ram.runtime = "10M"

[install]

[resources]
