#!/bin/bash

source "$(dirname "$0")/_common.sh"
source /usr/share/yunohost/helpers

ynh_backup "/etc/yunohost/apps/${app}"
catalogue="$(arcenal_fichier_catalogue)"
test ! -e "$catalogue" || ynh_backup "$catalogue"
