#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Vérification du catalogue ARCenal..."
arcenal_verifier_catalogue
arcenal_sauvegarder_catalogue
ynh_script_progression "Activation de l'ARCenal Store..."
arcenal_ecrire_catalogue
ynh_app_setting_set --key=catalogue_url --value="$(arcenal_url_catalogue)"
arcenal_actualiser_catalogue
ynh_script_progression "ARCenal Store est prêt."
